/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      "colors": {
        "on-background": "#1a1c1b",
        "on-surface-variant": "#414845",
        "outline": "#727975",
        "surface-container-high": "#e9e8e6",
        "surface-variant": "#e3e2e1",
        "tertiary": "#77534e",
        "tertiary-fixed": "#ffdad5",
        "inverse-on-surface": "#f1f1ef",
        "on-surface": "#1a1c1b",
        "surface-container-low": "#f4f3f2",
        "on-primary-fixed-variant": "#304c44",
        "surface": "#faf9f7",
        "primary-fixed-dim": "#aecdc2",
        "on-tertiary-fixed-variant": "#603e39",
        "surface-container-highest": "#e3e2e1",
        "on-secondary-fixed": "#301400",
        "secondary-fixed": "#ffdcc6",
        "surface-bright": "#faf9f7",
        "primary-fixed": "#c9eade",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#2e1411",
        "error": "#ba1a1a",
        "background": "#faf9f7",
        "tertiary-container": "#926b65",
        "inverse-surface": "#2f3130",
        "on-secondary": "#ffffff",
        "inverse-primary": "#aecdc2",
        "tertiary-fixed-dim": "#ebbcb5",
        "error-container": "#ffdad6",
        "secondary": "#85532e",
        "secondary-container": "#febb8e",
        "surface-tint": "#47645b",
        "on-error-container": "#93000a",
        "on-primary-container": "#f4fff9",
        "primary-container": "#5d7b71",
        "primary": "#456259",
        "on-secondary-container": "#794925",
        "outline-variant": "#c1c8c4",
        "surface-dim": "#dadad8",
        "on-tertiary": "#ffffff",
        "surface-container": "#eeeeec",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#022019",
        "on-secondary-fixed-variant": "#693c19",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed-dim": "#fbb88b",
        "surface-container-lowest": "#ffffff",
        "accent-peach": "#E8A87C",
        "sage-white": "#EEF1EC",
        "warm-charcoal": "#414845"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-margin": "24px",
        "stack-gap": "16px",
        "inline-gap": "12px",
        "card-padding": "20px",
        "section-gap": "40px"
      },
      "fontFamily": {
        "display": ["Literata", "serif"],
        "duration-display": ["Literata", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Literata", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Literata", "serif"],
        "headline-lg-mobile": ["Literata", "serif"]
      },
      "fontSize": {
        "display": ["42px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "duration-display": ["32px", {"lineHeight": "40px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "34px", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "30px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
